packages:
  - auth
  - auth/web
  - calendar
  - calendar/web
  - competition
  - course
  - course/web
  - competition/modules/documents/web
  - email
  - email/web
  - competition/modules/teams/web
  - competition/modules/inspection/web
  - landing
  - competition/modules/queue/web
  - competition/modules/registration/web
  - competition/modules/score/web
  - competition/modules/traffic/web

injectWorkspacePackages: true

allowBuilds:
  better-sqlite3: true
  esbuild: true
